In [235]:
import nibabel as nib
import numpy as np
from collections import OrderedDict

In [236]:
num_networks = 7

In [237]:
header_brain_path = 'hoAtlas/HarvardOxford-cort-prob-1mm.nii.gz'

In [238]:
header_brain_img = nib.load(header_brain_path)

In [239]:
header = header_brain_img.header

In [240]:
print(header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4 182 218 182  48   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  1.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 100.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL3.3'
aux_file        : b''
qform_code      : aligned
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 90.0
qoffset_y       : -126.0
qoffset_z       : -72.0
srow_x          : [-1.  0.  0. 90.

In [241]:
atlas_brain_path = 'schaeferAtlas/Schaefer2018_100Parcels_7Networks_order_FSLMNI152_1mm.nii.gz'

In [242]:
atlas_brain_img = nib.load(atlas_brain_path)
atlas_brain = atlas_brain_img.get_data()

    

In [243]:
print(atlas_brain_img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 182 218 182   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  0.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FreeSurfer May 13 2013'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 90.0
qoffset_y       : -126.0
qoffset_z       : -72.0
srow_x          : 

# ROI Number : Network Name

1-9, 51-58    : LH Visual  
10-15, 59-66  : Somatomotor  
16-23, 67-73  : Dorsal Attention  
24-30, 74-78  : Ventral Attention  
31-33, 79-80  : Limbic  
34-37,81-89   : Control  
38 -50, 90-100: DMN  

    
    
    

In [244]:
# Create an empty brain with zeros and populate it in the for loop later
# TODO

new_atlas = np.zeros((atlas_brain.shape[0],atlas_brain.shape[1],atlas_brain.shape[2],num_networks))
        

In [245]:
new_atlas.shape

(182, 218, 182, 7)

In [246]:
roi_network_dict = OrderedDict()

roi_network_dict['Visual'] =  np.concatenate((np.arange(1,10), np.arange(51,59)))
roi_network_dict['Somatomotor'] =  np.concatenate((np.arange(10,16), np.arange(59,67)))
roi_network_dict['DorsalAttention'] =  np.concatenate((np.arange(16,24), np.arange(67,74)))
roi_network_dict['VentralAttention'] =  np.concatenate((np.arange(24,31), np.arange(74,79)))
roi_network_dict['Limbic'] =  np.concatenate((np.arange(31,34), np.arange(79,81)))
roi_network_dict['Control'] =  np.concatenate((np.arange(34,38), np.arange(81,90)))
roi_network_dict['DMN'] =  np.concatenate((np.arange(38,51), np.arange(90,101)))


In [247]:
print(roi_network_dict)

OrderedDict([('Visual', array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 51, 52, 53, 54, 55, 56, 57, 58])), ('Somatomotor', array([10, 11, 12, 13, 14, 15, 59, 60, 61, 62, 63, 64, 65, 66])), ('DorsalAttention', array([16, 17, 18, 19, 20, 21, 22, 23, 67, 68, 69, 70, 71, 72, 73])), ('VentralAttention', array([24, 25, 26, 27, 28, 29, 30, 74, 75, 76, 77, 78])), ('Limbic', array([31, 32, 33, 79, 80])), ('Control', array([34, 35, 36, 37, 81, 82, 83, 84, 85, 86, 87, 88, 89])), ('DMN', array([ 38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]))])


In [248]:
for index, (network, roi_nos) in enumerate(roi_network_dict.items()):
    for roi in roi_nos:
        new_atlas[:,:,:,index][np.where(atlas_brain[:,:,:] == roi)] = 1
    print (index, network, roi_nos)



    
    

0 Visual [ 1  2  3  4  5  6  7  8  9 51 52 53 54 55 56 57 58]
1 Somatomotor [10 11 12 13 14 15 59 60 61 62 63 64 65 66]
2 DorsalAttention [16 17 18 19 20 21 22 23 67 68 69 70 71 72 73]
3 VentralAttention [24 25 26 27 28 29 30 74 75 76 77 78]
4 Limbic [31 32 33 79 80]
5 Control [34 35 36 37 81 82 83 84 85 86 87 88 89]
6 DMN [ 38  39  40  41  42  43  44  45  46  47  48  49  50  90  91  92  93  94
  95  96  97  98  99 100]


In [249]:
np.max(new_atlas[:,:,:,1])

1.0

In [250]:
new_header = atlas_brain_img.header

In [251]:
print(new_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 182 218 182   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  0.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FreeSurfer May 13 2013'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 90.0
qoffset_y       : -126.0
qoffset_z       : -72.0
srow_x          : 

In [252]:
new_header['dim'] = np.array([  4, 182, 218, 182,   num_networks,   1,   1,   1], dtype=np.int16)

In [253]:
new_header['descrip'] = b'4D Schaefer Atlas'

In [254]:
print(new_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  4 182 218 182   7   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  0.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'4D Schaefer Atlas'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 90.0
qoffset_y       : -126.0
qoffset_z       : -72.0
srow_x          : [-1. 

In [255]:
# Save a new brain

new_atlas_brain = nib.Nifti1Image(new_atlas, atlas_brain_img.affine, new_header)
nib.save(new_atlas_brain,'Schaefer_4d_Atlas_7_Networks.nii.gz')

In [256]:
from utils import atlasUtility as au

In [257]:
atlas_path = ['Schaefer_4d_Atlas_7_Networks.nii.gz']
atlas_label_Path = ['schaeferAtlas/Schaefer_4d_Atlas_7_Networks_1mm.xml']
schaefer_atlas_obj = au.queryAtlas(atlas_path, atlas_label_Path, True)

Atlas read
checked Pixel dimension


In [258]:
x,y,z = schaefer_atlas_obj.MNI2XYZ1mm([-6,-18,25])

In [259]:
schaefer_atlas_obj.get_neighbouring_coordinates(x,y,z, schaefer_atlas_obj.itr,0,1)

([6], [[96, 108, 99]], [[0, 0, -2]], [1.0])

In [271]:
schaefer_atlas_obj.getAtlasRegions([-1,-1,28])

(4, 'Ventral Attention', 0)

# DUMP

In [261]:
# a = nib.load(atlas_path[0]).get_data()

In [262]:
np.max(a)

1.0

In [263]:
nib.Nifti1Image?

In [264]:
np.where(np.array([[1,2],[2,2],[3,4]]) == 1)

(array([0]), array([0]))

In [265]:
a = np.array([[1,2],[2,2],[3,4]])
a

array([[1, 2],
       [2, 2],
       [3, 4]])

In [266]:
a[:,1][1] = 3
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [267]:
header['dim'] = np.array([  7, 182, 218, 182,  48,   1,   1,   1], dtype=np.int16)

In [268]:
nib.save(new_atlas, Schafer_atlas_7_vols.nii.gz)

NameError: name 'Schafer_atlas_7_vols' is not defined